#! /bin/bash

source ../../include/tmp.sh

function cleanup {
	killall -g test-chdir 2>/dev/null
	if [ -f tmp/chdir.txt ];
	then
		truncate --size 0 tmp/chdir.txt
	else
		touch tmp/chdir.txt
	fi

	if [ -d tmp/chdir-badperm ];
	then
		chmod 600 tmp/chdir-badperm
	else
		mkdir tmp/chdir-badperm
		chmod 600 tmp/chdir-badperm
	fi
	
}

cleanup

trap cleanup SIGTERM SIGABRT SIGQUIT SIGKILL SIGSEGV


(tail -f tmp/chdir.txt --pid=$(pidof test-chdir) | ./test-chdir $(mktemp -uq --tmpdir="/"))&

if [ "$(readlink /proc/$(pidof test-chdir)/cwd)"  = $(pwd) ];
then
	echo -n "a" >>tmp/chdir.txt
	if [ "$(readlink /proc/$(pidof test-chdir)/cwd)" = $(dirname $(pwd)) ];
	then
		echo -n "a" >>tmp/chdir.txt
		if [ "$(readlink /proc/$(pidof test-chdir)/cwd)" = "/" ];
		then
			killall test-chdir
			exit 0;
		else
			killall test-chdir
			echo "test-chdir unable to change to root directory";
			exit 1;
		fi
	else
		killall test-chdir
		echo "changed directory for test-chdir not correct";
		exit 1;
	fi
else
	killall test-chdir
	echo "Starting directory for test-chdir not correct"
	exit 1;
fi

