#! /bin/bash

source ../../include/tmp.sh

if [ ! -f './tmp/txt' ];
then
	touch tmp/txt
fi

./test-chmod

ls -ld ./tmp/txt | grep '.*-rw-rw-rw-.*' >>/dev/null
RET=$?

if [ "$RET" != "0" ];
then
	exit 1;
else 
	exit 0;
fi
