#! /bin/bash

source ../../include/tmp.sh

./test-creat

if [ -f './tmp/a' ];
then
	mode=$(ls -l ./tmp/a)	
	echo $mode | grep '.*-rwx------.*' >>/dev/null
	RET=$?
	if [ "$RET" = "0" ];
	then
		exit 0;
	else
		exit 1;
	fi
else
	exit 1;
fi
