#! /bin/bash

source ../../include/tmp.sh

umask 0000
if [ ! -f "tmp/z" ];
then
	touch tmp/z
fi

MSG=$(./test-creat)

if [ "$?" != "0" ];
then
	exit 1;
fi
echo "$MSG"

function testmode {
	FILE=$1
	PERM=$2
	if [ -f "$FILE" ];
	then
		mode=$(ls -l $FILE)	
		echo $mode | grep "$PERM" >>/dev/null
		RET=$?
		if [ "$RET" = "0" ];
		then
			return 0;
		else
			echo "$1 failed to be created or has the wrong permissions";
			exit 1;
		fi
	else
		echo "$1 failed to be created or has the wrong permissions";
		exit 1;
	fi
}

testmode ./tmp/a '.*-rwx------.*'
testmode ./tmp/b '.*-rw-------.*'
testmode ./tmp/c '.*-r-x------.*'
testmode ./tmp/d '.*-r--------.*'
testmode ./tmp/e '.*--wx------.*'
testmode ./tmp/f '.*--w-------.*'
testmode ./tmp/g '.*---x------.*'
testmode ./tmp/h '.*----------.*'
testmode ./tmp/i '.*----rwx---.*'
testmode ./tmp/j '.*----rw----.*'
testmode ./tmp/k '.*----r-x---.*'
testmode ./tmp/l '.*----r-----.*'
testmode ./tmp/m '.*-----wx---.*'
testmode ./tmp/n '.*-----w----.*'
testmode ./tmp/o '.*------x---.*'
testmode ./tmp/p '.*-------rwx.*'
testmode ./tmp/q '.*-------rw-.*'
testmode ./tmp/r '.*-------r-x.*'
testmode ./tmp/s '.*-------r--.*'
testmode ./tmp/t '.*--------wx.*'
testmode ./tmp/u '.*--------w-.*'
testmode ./tmp/v '.*---------x.*'
