#! /bin/bash

touch tmp/xyzzy
touch tmp/xyzzy3
mkdir tmp/xyzzy4
chmod 0300 tmp/xyzzy3
./test-open&

PID=$(pidof test-open)
POINT=$(readlink /proc/$PID/fd/3)
if [ "$POINT" = "$(realpath tmp/xyzzy)" ];
then
	kill $PID
	exit 0;
else
	kill $PID
	exit 1;
fi
