#! /bin/bash

source ../../include/tmp.sh

if [ ! -p ./tmp/read-eagain.txt ];
then
	mkfifo ./tmp/read-eagain.txt
fi

#cat >>./tmp/read-eagain.txt&
./test-read-eagain
[ "$$"!=0 ] && (killall cat ; exit 1)
#killall cat
exit 0
