#! /bin/bash

NUMS=$(seq 0 $RANDOM | tr '\n' ' ')
OUT=$(./test-argv $NUMS )
NUMS=$(echo "$NUMS" | tr ' ' '\n')
TMP1=$(mktemp)
trap "rm $TMP1" EXIT
TMP2=$(mktemp)
trap "rm $TMP1 ; rm $TMP2" EXIT 

echo "$OUT" >$TMP1
echo "$NUMS" >$TMP2

cmp $TMP1 $TMP2 >/dev/null 2>/dev/null

if [ "$?" = 0 ];
then 
	exit 0
else
	exit 1
fi
