.TH ERRORS 5 "November 2013" nlibc
.SH DESCRIPTION
The errors file found in the topmost directory of the project contains a list
of the names of every macro that is in the standard C environment that is to
be included into the project. To add another macro simply append the macro name to the end of the list, and run 'make include/stddef.h'.
